### ISSUE TITLE
Child theme

### ISSUE THREAD

**Issue by ludoo0d0a** [ThemeBoy/Rookie#26]
To create a child theme form rookie is a hard task because of rookie_scripts().

It will be better if we could load the main style with get_template_directory_uri instead get_stylesheet_uri, so that loading from child theme it won't load the child style.css but the parent stylesheet.
```php
	// Load our main stylesheet.
	//wp_enqueue_style( 'rookie-style', get_stylesheet_uri() );
wp_enqueue_style( 'rookie-style', get_template_directory_uri() . '/style.css' );
```

With this fix, and Child Theme Configurator plugin, and "Enqueue child stylesheet" in "Stylesheet handling" option, functions.php code will look like this, and loads stylesheets pretty well :

```php
if ( !function_exists( 'chld_thm_cfg_child_css' ) ):
    function chld_thm_cfg_child_css() {
        wp_enqueue_style( 'chld_thm_cfg_child', get_stylesheet_uri() ); 
    }
endif;
add_action( 'wp_enqueue_scripts', 'chld_thm_cfg_child_css', 999 );
```

**Comment by brianmiyaji** [comment]
@ludoo0d0a The child theme template has been updated to load the parent stylesheet, check out https://github.com/ThemeBoy/Rookie-Child/commit/51b817dace9fd8456baf2f7fa3d4def2549a2cba

**Comment by ludoo0d0a** [comment]
Thanks but it does'nt work.

in main parent Rookie template, this line will enqueue style.css from CHILD theme, and NOT the style.css from the parent itself (with its framework)

> wp_enqueue_style( 'rookie-style', get_stylesheet_uri() );

because as wrtitten in [doc ](https://codex.wordpress.org/Function_Reference/get_stylesheet_directory_uri)
get_stylesheet_directory_uri will return the child's theme directory URI

**Comment by ludoo0d0a** [comment]
Thanks it seems to be ok now.
